### ISSUE TITLE
caddyserver.com registration

### ISSUE THREAD

**Issue by ireneu** [caddy-dns/infomaniak#1]
Hi, could you please register this provider on caddyserver.com?

Otherwise `caddy upgrade` is broken on custom builds that include this module.

See also: https://github.com/caddy-dns/acmeproxy/issues/2

**Comment by jangzn** [comment]
Hi!

Thanks for bringing this to my attention and for the link. I'll look into it.

**Comment by jangzn** [comment]
I was able to reproduce the behavior. Claiming the package as mentioned in [caddy-dns/acmeproxy#2](https://github.com/caddy-dns/acmeproxy/issues/2) resolved the issue and the `caddy upgrade` command ran through for me. @ireneu, please just reopen this in case the issue persists for you.

**Comment by mholt** [comment]
Cool, thanks for doing this, @jangzn !

**Comment by ireneu** [comment]
Awesome, thank you!
